---
layout: ../../layouts/PostLayout.astro
title: 'Callbacks & Events'
pubDate: 2022-07-01
description: 'A callback é o mecanismo básico no qual todos outros mecanismos assincronos são baseados. Sem as callbacks, não teriamos Promises, e portanto nem async/await.'
author: 'marcos'
slug: 'callbacks-e-events'
image:
    url: 'https://docs.astro.build/assets/full-logo-light.png'
    alt: 'The full Astro logo.'
tags: ["astro", "blogging", "learning in public"]
---

## O padrão Callback
Callbacks são funções que são invocadas para propagar o resultado de uma operação. No mundo assincrono, elas substituem o uso da instrução `return`, que por sua vez, sempre executam de forma síncrona.
JavaScript é a linguagem ideal para callbacks pois funções são objetos first-class e podem facilmente serem atribuidas à variáveis, passadas como argumentos, etc. Além de também possuir **closures**, que é uma construção ideal para implementar callbacks. Com closures, podemos referenciar o ambiente no qual uma função foi criada, desta forma, podemos sempre manter o contexto no qual a operação assincrona foi requisitada, não importa aonde ou quando a callback for invocada.

### O estilo continuation-passing
Em JavaScript, uma callback é uma função passada como argumento para outra função, a mesma será invocada com o resultado da operação quando ela se completar.
Em programação funcional, esta forma de propagar o resultado é chamada de **continuation-passing style (CPS)**.

Este estilo é um conceito geral, e não está sempre associado com operações assincronas. Na verdade, ela simplesmente indica que o resultado é propagado passando-o para outra função (no caso a callback), ao invés de diretamente retornar ao caller.

### CPS Síncrono
Para clarificar o conceito, vamos mostrar uma função síncrona utilizando estilo direto, e depois a com CPS.

```js
function add(a, b) {
    return a + b
}
```

O equivalente CPS da função seria:

```js
function addCps(a, b, callback) {
    callback(a + b)
}
```

A função `addCps` é uma função CPS síncrona. Síncrona pois irá completar sua execução somente quando a callback completar sua execução também.

### CPS Assíncrono
Vamos considerar o caso onde a função `addCps()` é assíncrona.

```js
function addAsync(a, b, callback) {
    setTimeout(() => callback(a + b), 100)
}
```

`setTimeout()` adiciona uma task à event queue que será executada após um dado número de millisegundos. Isto é claramente uma operação assíncrona:

```js
console.log('before')
additionAsync(1, 2, result => console.log(`Result: ${result}`))
console.log('after')
```

Output:
```bash
before
after
Result: 3
```

Como `setTimeout` engatilha uma operação assíncrona, ela não espera pela callback ser executada. Na verdade ela retorna imediatamente, dando controle de volta à `addAsync()`, e então novamente ao seu caller. Esta propriedade em Node.js é crucical, já que ela devolve o controle ao event loop assim que uma requisição assíncrona é enviada, portanto permitindo que novos eventos na queue sejam processados.

Quando a operação assíncrona finalmente se completar, a execução é então resumida, começando apartir da callback fornecida à função assíncrona que causou sua invocação.


## Síncrono ou Assíncrono?
A ordem de execução das instruções muda radicalmente dependendo da natureza de uma função - síncrona ou assíncrona. Isto tem fortes repercusões no fluxo de toda a aplicação, ambos em termos de exatidão e eficiência.

Vamos analisar estes dois paradigmas e suas desvantagens.
Em geral, o que deve ser evitado é criar inconsistência e confusão entre a natureza de uma API.

### Uma função imprevisível
Uma das situações mais perigosas é possuir uma API que se comporta de forma síncrona sobre certas condições e assíncrona em outras:

```js
import {readFile} from 'fs'

const cache = new Map()

function inconsistentRead(filename, cb) {
    if(cache.has(filename)) {
        cb(cache.get(filename)) // CPS Síncrono
    } else {
        readFile(filename, 'utf-8', (err, data) => {
            cache.set(filename, data)
            cb(data)
        })
    }
}
```

A função anterior é perigosa pois se comporta de forma assíncrona até que o arquivo seja lido pela primeira vez e o cache set setado, mas síncrona para todas as requisições subsequentes quando o conteúdo do arquivo já estiver em cache.


### Libertando Zalgo
Considere o seguinte código:

```js
function createFileReader (filename) {
  const listeners = []
  inconsistentRead(filename, value => {
    listeners.forEach(listener => listener(value))
  })
  return {
    onDataReady: listener => listeners.push(listener)
  }
}
```

Quando a função anterior é invocada, ela cria um novo objeto que age como um notificador, nos permitindo setar multiplos listeners para um operação de leitura de arquivo. Todos os listeneres serão invocados de uma vez quando a operação de leitura terminar e os dados estiverem disponíveis:

```js
const reader1 = createFileReader('data.txt')
reader1.onDataReady(data => {
  console.log(`First call data: ${data}`)
  // ...sometime later we try to read again from
  // the same file
  const reader2 = createFileReader('data.txt')
  reader2.onDataReady(data => {
    console.log(`Second call data: ${data}`)
  })
})
```

Output:
```bash
First call data: some data
```

Como podemos ver, a callback do segundo reader nunca é invocada. Porque:

- Durante a criação de `reader1`, nossa função `inconsistentRead()` se comporta de forma assíncrona pois não existe resultados cached disponíveis. isto significa que qualquer listener `onDataReady` será invocado depois em outro ciclo do event loop, portanto temos todo o tempo que precisamos para registrar nosso listener.
- Depois, `reader2` é criado no ciclo do event loop em que o cache para o arquivo requisitado já existe. Neste caso, a chamada interior para `inconsistentRead()` será síncrona. Portanto sua callback será invocada imediatamente, o que significa que todos os listeners de `reader2` serão invocadas síncronamente também. Porém, estamos registrando o listener após a criação de `reader2`, portanto nunca serão invocados.

O comportamento da função `inconsistentRead()` é muito imprevisível, e o bug que acabamos de ver pode ser extremamente complicado de identificar e reproduzit em uma aplicação real.

### Usando APIs síncronas
A lição aqui é que é imperativo para uma API claramente definir sua natureza.

Uma possível solução para nossa função `inconsistenRead()` é fazê-la completamente síncrona:

```js
import { readFileSync } from 'fs'
const cache = new Map()
function consistentReadSync (filename) {
  if (cache.has(filename)) {
    return cache.get(filename)
  } else {
    const data = readFileSync(filename, 'utf8')
    cache.set(filename, data)
    return data
  }
}
```

Note como ela também foi convertida para o estilo direto. è sempre uma boa prática implementar uma API síncrona utilizando o estilo direto. Isto irá eliminar qualquer confusão sobre sua natureza e também será mais eficiente de uma perspectiva de performance.

Além de ter de mudar nossa interface na API do `createFileReader()`, existem outras armadilhas em se usar uma API síncrona:

- Uma API síncrona para uma funcionalidade específica pode não ser disponível.
- Uma API síncrone irá bloquear o event loop e colocar quaisquer outras requisições concorrentes em espera. Isto quebra o modelo de concorrência de Node.js, desacelerando toda a aplicação.

Usar um I/O síncrono em Node.js é desencourajado em muitas circunstâncias, mas em algumas, pode ser a mais fácil e mais eficiente solução. Sempre avalie seu caso específico e escolha a alternativa correta. Como exemplo, faria total sentido usar uma API síncrona blocante para carregar um arquivo de configuração em startup time.

### Garantindo assíncronicidade com execução deferida
Outra alternativa para consertar nossa função é fazê-la puramente assíncrona. O truque aqui é agendar à invocação da callback síncrona para o "futuro" ao invés de rodá-la imediatamente no mesmo ciclo do event loop. Em Node.js, isto é possível com `process.nextTick()`, que defere a execução de uma função após a operação atual terminar:

```js
import { readFile } from 'fs'
const cache = new Map()
function consistentReadAsync (filename, callback) {
  if (cache.has(filename)) {
    // deferred callback invocation
    process.nextTick(() => callback(cache.get(filename)))
  } else {
    // asynchronous function
    readFile(filename, 'utf8', (err, data) => {
      cache.set(filename, data)
      callback(data)
    })
  }
}
```

Agora, graças ao `process.nextTick()`, nossa função é garantida de invocar sua callback de forma assíncrona, sob quaisquer circunstâncias. 


## Convenções de Callback em Node.js
Em Node.js, APIs CPS e callbacks seguem um conjunto de convenções específicas.

### A callback vem por último
Em todas funções core Node.js, a convenção é que quando uma função aceita uma callback, ela tem de ser passada como o último argumento.

```js
readFile(filename, [options], callback)
```

### Qualquer erro sempre vem primeiro
Em CPS, erros produzidos por uma função CPS são sempre passados como o primeiro argumento da callback, e qualquer resultado real é passado começando do segundo argumento. Se a operação se completa sem erros, o primeiro argumento será `null` ou `undefined`. 

```js
readFile('foo.txt', 'utf8', (err, data) => {
  if(err) {
    handleError(err)
  } else {
    processData(data)
  }
})
```

É boa prática sempre checar a presença de um erro, já que não fazer isto torna mais díficil encontrar possíveis pontos de falha. Outra convenção importante é que o erro deve sempre ser do tipo `Error`.

### Propagando erros
Propagar erros em funções síncronas diretas é feito com a statement `throw`, que causa o erro pular acima na call stack até que ele seja pego.

Em CPS assíncrono, porém, propagação de erro correta é feita simplesmente passando o erro à proxima callback na corrente. O padrão típico é:

```js
import { readFile } from 'fs'

function readJSON (filename, callback) {
  readFile(filename, 'utf8', (err, data) => {
    let parsed
    if (err) {
      // propagate the error and exit the current function
      return callback(err)
    }
    try {
      // parse the file contents
      parsed = JSON.parse(data)
    } catch (err) {
      // catch parsing errors
      return callback(err)
    }
    // no errors, propagate just the data
    callback(null, parsed)
  })
}
```

Note como não usamos `throw` nem `return`. Note também como usamos a statement `try...catch` para pegar quaisquer erros vindos de `JSON.parse()`, que é uma função síncrona e portanto usa a tradicional instrução `throw` para propagar erros ao caller.
Finalmente, se tudo deu certo, `callback` é invocada com `null` no primeiro argumento indicando que não houveram erros.

## O Padrão Observer
Em conjunto com o padrão Reactor e callbacks, o padrão Observer é um requisito absoluto para masterizar Node.js.

O padrão Observer é a solução ideal para modelar a natureza reativa de Node.js e é um complemento para callbacks.

> O padrão Observer define um objeto (chamado sujeito) que pode notificar um conjunto de observadores (ou listeners) quando uma mudança em seu estado ocorre.

A diferença principal do padrão Callback é que o sujeito pode notificar multiplos observadores, enquanto que callbacks geralmente propagam seu resultado para apenas um listener, a callback.


### O EventEmitter
Em Node.js, o padrão Observer é facilmente utilizado pois ele está construido na core e disponível através da classe `EventEmitter`. A classe `EventEmitter` nos permite registrar uma ou mais funções como listeners, que serão invocados quando um tipo de evento em particular for atirado.

```js
import { EventEmitter } from 'events'
const emitter = new EventEmitter()
```

Os métodos essencias de `EventEmitter` são:

- `on(event, listener)`: registra um novo listener (uma função) para o tipo de evento dado (string).
- `once(event, listener)`: registra um novo listener, que é então removido após o evento ser emitido pela primeira vez.
- `emit(event, [arg1], [...])`: produz um novo evento e fornece argumentos adicionais que serão passados aos listeners.
- `removeListener(event, listener)`: remove um listener do tipo de evento especificado.

A função `listener` possui a assinatura `function([arg1], [...])`, portanto ela simplesmente aceita os argumentos fornecidos pelo emissor do evento.

### Criando e usando o EventEmitter

#### Usando uma instância
```js
import { EventEmitter } from 'events'
import { readFile } from 'fs'
function findRegex (files, regex) {
  const emitter = new EventEmitter()
  for (const file of files) {
    readFile(file, 'utf8', (err, content) => {
      if (err) {
        return emitter.emit('error', err)
      }
      emitter.emit('fileread', file)
      const match = content.match(regex)
      if (match) {
        match.forEach(elem => emitter.emit('found', file, elem))
      }
    })
  }
  return emitter
}
```

A função que definimos acima retorna uma instância de um EventEmitter que irá produzir três tipos de eventos:

- `fileread`, quando um arquivo estiver sendo lido.
- `found`, quando um match for encontrado.
- `error`, quando um erro ocorrer durante a leitura do arquivo.

A função pode ser usada desta forma:

```js
findRegex(
  ['fileA.txt', 'fileB.json'],
  /hello \w+/g
)
  .on('fileread', file => console.log(`${file} was read`))
  .on('found', (file, match) => console.log(`Matched "${match}" in ${file}`))
  .on('error', err => console.error(`Error emitted ${err.message}`))
```

#### Usando uma classe
O EventEmitter é raramente usado por si só, como no exemplo anterior. Na verdade, é mais comum ve-lo extendido por outras classes. Na prática, isto permite qualquer classe herdar as capacidades do EventEmitter, portanto se tornando um objeto observável.

```js
import { EventEmitter } from 'events'
import { readFile } from 'fs'
class FindRegex extends EventEmitter {
  constructor (regex) {
    super()
    this.regex = regex
    this.files = []
  }
  addFile (file) {
    this.files.push(file)
    return this
  }
  find () {
    for (const file of this.files) {
      readFile(file, 'utf8', (err, content) => {
        if (err) {
          return this.emit('error', err)
        }
        this.emit('fileread', file)
        const match = content.match(this.regex)
        if (match) {
          match.forEach(elem => this.emit('found', file, elem))
        }
      })
    }
    return this
  }
}
```

E usamos desta forma:

```js
const findRegexInstance = new FindRegex(/hello \w+/)
findRegexInstance
  .addFile('fileA.txt')
  .addFile('fileB.json')
  .find()
  .on('found', (file, match) => console.log(`Matched "${match}" in file ${file}`))
  .on('error', err => console.error(`Error emitted ${err.message}`))
```

### Propagando erros
Assim como com callbacks, o EventEmitter não pode apenas `throw` uma exceção quando um erro ocorre. Ao invés disto, a convenção é emitir um evento especial, chamado `error`, e passar um objeto `Error` como argumento.

> O `EventEmitter` trata o evento `error` de forma especial. Ele irá automaticamente `throw` uma exceção e sair da aplicação se nenhum listener associado for achado. Por esta razão, é recomendado sempre registrar um listener para o evento `error`.

{/* ### Eventos Síncronos e Assíncronos
Assim como com callbacks, eventos podem ser emitidos de forma síncrona ou assíncrona. É crucial que nunca misturemos as duas abordagens no mesmo `EventEmitter`, mas ainda mais importante, devemos nunca emitir o mesmo tipo de evento usando um mix de código síncrono e assíncrono. A diferença principal entre emitir eventos síncronos e assíncronos encontra-se na forma como os listeners são registrados. */}

## EventEmitter vs Callbacks
Um dilema comum quando definimos uma API assíncrona é decidindo se usamos um `EventEmitter` ou se simplesmente aceitaremos uma callback.
A regra geral é semântica:
- Callbacks para quando o resultado deve ser retornado de forma assíncrona
- Eventos quando temos uma necessidade de comunicar que algo aconteceu.

Mas além deste príncipio simples, aqui vão outras dicas para ajudar na seleção do método:

- Usamos `events` quando precisamos suportar diferentes tipos de eventos, com callbacks fariamos aceitando diversas callbacks diferentes para serem chamadas, porém isto não é muito elegante.
- `EventEmitter` deve ser usado quando o mesmo evento pode ocorrer multiplas vezes, ou pode não ocorrer nunca. Uma callback espera ser invocada exatamente uma vez.
- Uma API que usa callbacks pode notificar apenas uma callback em particular, `EventEmitter` permite registrar múltiplos listeners para o mesmo evento.

### Combinando callbacks e events
Existem algumas circunstâncias onde o `EventEmitter` pode ser usado em conjunto com uma callback. Este padrão é extremamente poderoso já que nos permite passar um resultado de forma assíncrona usando uma callback tradicional, e ao mesmo tempo retornar um `EventEmitter`, que pode ser usado para fornecer maiores detalhes sobre o status de um processo assíncrono.
Um exemplo deste padrão é oferecido pelo pacote `glob`, uma bibloteca que performa buscas glob-style em arquivos:

```js
import glob from 'glob'
glob('data/*.txt',
  (err, files) => {
    if (err) {
      return console.error(err)
    }
    console.log(`All files found: ${JSON.stringify(files)}`)
  })
  .on('match', match => console.log(`Match found: ${match}`))
```

Combinar um `EventEmitter` com callbacks tradicionais é uma forma elegante de se oferecer duas abordagens diferentes na mesma API. Uma abordagem é geralmente para um uso mais simples e imediato, enquanto a outra é para aqueles cenários mais avançados/detalhados.

